"""add phone to users

Revision ID: bcd1e0efb2c5
Revises: 2ff693a66281
Create Date: 2026-10-08 17:47:22.889805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd1e0efb2c5'
down_revision: Union[str, Sequence[str], None] = '2ff693a66281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'phone')
    # ### end Alembic commands ###
